app.name=Transaction Rule Processor
db.url=jdbc:h2:./data/transactions;MODE=PostgreSQL;AUTO_SERVER=TRUE
db.driver=org.h2.Driver
db.username=sa
db.password=xxxxxxxx
parallelism=4
rules.directory=rules
output.directory=output
